# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
run:
  concurrency: 4
  allow-parallel-runners: true
  timeout: 4m
issues:
  exclude-dirs-use-default: true
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - copyloopvar
    - godot
    - gofmt
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - govet
